---
- name: launch instance
  local_action:
    module: ec2
    group: "{{ security_group }}"
    instance_type: "{{ instance_type}}"
    image: "{{ image }}"
    wait: true
    region: "{{ region }}"
    zone: "{{ zone | default(omit) }}"
    keypair: "{{ keypair }}"
    count: "{{ count }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ volume_size | default('8') }}"
        delete_on_termination: true
  register: ec2

- name: add group to the inventory
  with_items: ec2.instances
  local_action: lineinfile
                dest="inventory/production"
                line="[{{ instance_role }}]"
                state="present"

- name: add ip to the host in the inventory
  with_items: ec2.instances
  local_action: lineinfile
                dest="inventory/production"
                insertafter="^\[{{ instance_role }}\]"
                line="{{ item.public_ip }} private_ip={{ item.private_ip }} instance_id={{item.id}}"

- name: wait for ssh
  with_items: ec2.instances
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started

- name: tag instance
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: ec2.instances
  args:
    tags:
      Name: "{{ instance_role }}"
      Group: "{{ group_tag }}"

- name: tag root volume
  local_action:
    module: ec2_tag
    resource: "{{ item['block_device_mapping'][item['root_device_name']]['volume_id'] }}"
    region: "{{ region }}"
    state: present
    tags:
      Name: "{{ instance_role }}-root"
      Group: "{{ group_tag }}"
  with_items: ec2.instances
